version: '3.8'

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: processapedidosdb
      POSTGRES_PASSWORD: processapedidosdb
      POSTGRES_DB: processa_pedidos
    ports:
      - "5433:5432"
    volumes:
      - ./init-db:/docker-entrypoint-initdb.d
